/-!
  A reusable symbolic strategy framework for the NesyLink mathematical logic
  project.

  The task-specific Lean files prove concrete stage-machine policies for
  task_1 through task_5. This file factors out the common proof layer:

  * executing an explicit plan;
  * extracting a finite trace from a state-driven policy;
  * checking that all actions along a trace satisfy an action mask;
  * proving bounded completeness of breadth-first symbolic search.

  The BFS theorem is intentionally stated for an abstract deterministic
  transition function. This matches the project's verified layer: each task
  supplies its own symbolic state, action type, transition function, action
  mask, and goal predicate.
-/

namespace StrategyFramework

section Generic

variable {State Action : Type}

/-! ### Plan and policy execution -/

/-- Execute a finite list of actions from an initial symbolic state. -/
def runPlan (step : State → Action → State) : State → List Action → State
  | s, [] => s
  | s, a :: rest => runPlan step (step s a) rest

/-- Extract the first `n` actions generated by a state-driven policy. -/
def policyTrace
    (policy : State → Action)
    (step : State → Action → State) :
    Nat → State → List Action
  | 0, _ => []
  | n + 1, s =>
      let a := policy s
      a :: policyTrace policy step n (step s a)

/-- Run a state-driven policy for exactly `n` symbolic steps. -/
def runPolicy
    (policy : State → Action)
    (step : State → Action → State) :
    Nat → State → State
  | 0, s => s
  | n + 1, s => runPolicy policy step n (step s (policy s))

theorem policyTrace_length
    (policy : State → Action)
    (step : State → Action → State) :
    ∀ n s, (policyTrace policy step n s).length = n := by
  intro n
  induction n with
  | zero =>
      intro s
      rfl
  | succ n ih =>
      intro s
      simp [policyTrace, ih]

theorem runPolicy_eq_runPlan_policyTrace
    (policy : State → Action)
    (step : State → Action → State) :
    ∀ n s,
      runPolicy policy step n s =
        runPlan step s (policyTrace policy step n s) := by
  intro n
  induction n with
  | zero =>
      intro s
      rfl
  | succ n ih =>
      intro s
      simp [runPolicy, policyTrace, runPlan, ih]

/-! ### Action-mask certificates -/

/--
Check that every action in a finite plan is enabled at the state where it is
executed. The task files instantiate `enabled` with their symbolic precondition
checks, such as key, bridge, button, and chest conditions.
-/
def actionsEnabledAlong
    (enabled : State → Action → Bool)
    (step : State → Action → State) :
    State → List Action → Bool
  | _, [] => true
  | s, a :: rest =>
      enabled s a && actionsEnabledAlong enabled step (step s a) rest

def SafeTrace
    (enabled : State → Action → Bool)
    (step : State → Action → State)
    (init : State)
    (plan : List Action) : Prop :=
  actionsEnabledAlong enabled step init plan = true

theorem policyTrace_safety_certificate
    (enabled : State → Action → Bool)
    (policy : State → Action)
    (step : State → Action → State)
    (init : State)
    (n : Nat)
    (h :
      actionsEnabledAlong enabled step init
        (policyTrace policy step n init) = true) :
    SafeTrace enabled step init (policyTrace policy step n init) := by
  exact h

/-! ### Bounded reachability and BFS completeness -/

/-- A target state is reachable by some plan of length at most `n`. -/
def BoundedReachable
    (step : State → Action → State)
    (init : State)
    (n : Nat)
    (target : State) : Prop :=
  ∃ plan, plan.length ≤ n ∧ runPlan step init plan = target

/-- A goal state is reachable by some plan of length at most `n`. -/
def BoundedGoalReachable
    (step : State → Action → State)
    (goal : State → Prop)
    (init : State)
    (n : Nat) : Prop :=
  ∃ final, BoundedReachable step init n final ∧ goal final

/-- One BFS expansion layer from a frontier, using the complete action list. -/
def expandFrontier
    (step : State → Action → State)
    (actions : List Action) :
    List State → List State
  | [] => []
  | s :: rest => actions.map (step s) ++ expandFrontier step actions rest

/--
All states visited by a depth-limited BFS. The definition keeps earlier
frontiers in the list, so a goal found at depth less than `n` remains visible
at depth `n`.
-/
def bfsVisited
    (step : State → Action → State)
    (actions : List Action) :
    Nat → List State → List State
  | 0, frontier => frontier
  | n + 1, frontier =>
      frontier ++ bfsVisited step actions n (expandFrontier step actions frontier)

def bfsVisitedFrom
    (step : State → Action → State)
    (actions : List Action)
    (init : State)
    (n : Nat) : List State :=
  bfsVisited step actions n [init]

def BfsFrontierComplete
    (step : State → Action → State)
    (init : State)
    (n : Nat)
    (visited : List State) : Prop :=
  ∀ target, BoundedReachable step init n target → target ∈ visited

def BfsFindsGoal
    (goal : State → Prop)
    (visited : List State) : Prop :=
  ∃ final, final ∈ visited ∧ goal final

theorem mem_expandFrontier_of_mem
    (step : State → Action → State)
    (actions : List Action)
    (hActions : ∀ a : Action, a ∈ actions)
    (a : Action)
    {s : State}
    {frontier : List State}
    (hs : s ∈ frontier) :
    step s a ∈ expandFrontier step actions frontier := by
  induction frontier with
  | nil =>
      cases hs
  | cons head tail ih =>
      simp [expandFrontier] at hs ⊢
      rcases hs with hEq | hTail
      · subst hEq
        exact Or.inl ⟨a, hActions a, rfl⟩
      · exact Or.inr (ih hTail)

theorem runPlan_mem_bfsVisited_of_mem
    (step : State → Action → State)
    (actions : List Action)
    (hActions : ∀ a : Action, a ∈ actions)
    (plan : List Action)
    {n : Nat}
    {s : State}
    {frontier : List State}
    (hs : s ∈ frontier)
    (hlen : plan.length ≤ n) :
    runPlan step s plan ∈ bfsVisited step actions n frontier := by
  induction n generalizing s frontier plan with
  | zero =>
      cases plan with
      | nil =>
          simpa [runPlan, bfsVisited] using hs
      | cons _ _ =>
          cases hlen
  | succ n ih =>
      cases plan with
      | nil =>
          simp [runPlan, bfsVisited, hs]
      | cons a rest =>
          have hRestLen : rest.length ≤ n := Nat.succ_le_succ_iff.mp hlen
          have hStepMem :
              step s a ∈ expandFrontier step actions frontier :=
            mem_expandFrontier_of_mem step actions hActions a hs
          have hRest :
              runPlan step (step s a) rest ∈
                bfsVisited step actions n
                  (expandFrontier step actions frontier) :=
            ih rest hStepMem hRestLen
          simp [runPlan, bfsVisited]
          exact Or.inr hRest

theorem bfsVisited_frontier_invariant
    (step : State → Action → State)
    (actions : List Action)
    (hActions : ∀ a : Action, a ∈ actions)
    (init : State)
    (n : Nat) :
    BfsFrontierComplete step init n (bfsVisitedFrom step actions init n) := by
  intro target hreachable
  rcases hreachable with ⟨plan, hlen, hrun⟩
  rw [← hrun]
  exact runPlan_mem_bfsVisited_of_mem
    step actions hActions plan
    (s := init)
    (frontier := [init])
    (by simp)
    hlen

/--
Bounded BFS completeness: if a goal can be reached by some plan of length at
most `n`, and the action list covers every action, then depth-`n` BFS will have
visited a goal state.
-/
theorem bfsVisited_complete_for_bounded_goal
    (step : State → Action → State)
    (actions : List Action)
    (hActions : ∀ a : Action, a ∈ actions)
    (goal : State → Prop)
    {init : State}
    {n : Nat}
    (hreachable : BoundedGoalReachable step goal init n) :
    BfsFindsGoal goal (bfsVisitedFrom step actions init n) := by
  rcases hreachable with ⟨final, hbounded, hgoal⟩
  exact ⟨
    final,
    bfsVisited_frontier_invariant step actions hActions init n final hbounded,
    hgoal
  ⟩

/--
A completed deterministic policy induces a bounded reachable goal. This bridges
the task-specific `symbolicPolicy` proofs to the generic BFS theorem above.
-/
theorem policy_completion_is_bounded_goal
    (policy : State → Action)
    (step : State → Action → State)
    (goal : State → Prop)
    (init : State)
    (n : Nat)
    (hgoal : goal (runPolicy policy step n init)) :
    BoundedGoalReachable step goal init n := by
  refine ⟨runPolicy policy step n init, ?_, hgoal⟩
  refine ⟨policyTrace policy step n init, ?_, ?_⟩
  · rw [policyTrace_length]
    exact Nat.le_refl n
  · exact (runPolicy_eq_runPlan_policyTrace policy step n init).symm

/--
If a state-driven policy reaches a goal in `n` steps, then a complete bounded
BFS over the same symbolic transition layer also finds a goal within `n` steps.
-/
theorem bfs_finds_goal_reached_by_policy
    (policy : State → Action)
    (step : State → Action → State)
    (actions : List Action)
    (hActions : ∀ a : Action, a ∈ actions)
    (goal : State → Prop)
    (init : State)
    (n : Nat)
    (hgoal : goal (runPolicy policy step n init)) :
    BfsFindsGoal goal (bfsVisitedFrom step actions init n) := by
  exact bfsVisited_complete_for_bounded_goal
    step actions hActions goal
    (policy_completion_is_bounded_goal policy step goal init n hgoal)

end Generic

end StrategyFramework
